### ISSUE TITLE
Incompatibility with Qiskit 1.0

### ISSUE THREAD

**Issue by trbromley** [QuTech-Delft/pennylane-quantuminspire#143]
The failures of this plugin in the [test matrix](https://github.com/PennyLaneAI/plugin-test-matrix?tab=readme-ov-file#testing-matrix) are ultimately because of Qiskit 1.0.

Currently, this plugin is relying on [pennylane-qiskit](https://github.com/PennyLaneAI/pennylane-qiskit), which does not pin to Qiskit `<1.0` as a dependency. We do this because part of the plugin is compatible with 1.0 and the other part is not (which is taken care of in the CI). Our plan is for all of pennylane-qiskit to work with 1.0, but this will likely not happen until the end of March.

In the meantime, it might make sense for this plugin to pin to `<1.0` Qiskit in `setup.py`.

**Comment by QFer** [comment]
Thanks, for reporting this. we indeed updated quantuminspire SDK to remain compatible with Qiskits latest updates. We will see if we can add the pin to let it work again (at least the latest version).

**Comment by QFer** [comment]
Monday May 27th: all tests in the matrix passed successfully. Last week we saw some fails we cannot solve in the plugin. 

Sometimes a test fails because the answer is slightly out of the range of the accepted values. Sometimes the Quantum Inspire backend was not responding (or unreachable).
