### ISSUE TITLE
ImportError: cannot import name 'ProviderV1' from 'qiskit.providers'

### ISSUE THREAD

**Issue by astralcai** [QuTech-Delft/pennylane-quantuminspire#149]
Plugin tests have been failing due to a qiskit related import error:
https://github.com/PennyLaneAI/plugin-test-matrix/actions/runs/8577156138/job/23509314951

**Comment by QFer** [comment]
We are working on the problem. (created https://github.com/QuTech-Delft/pennylane-quantuminspire/pull/150 for it).

**Comment by QFer** [comment]
Monday May 27th: all tests in the matrix passed successfully. Last week we saw some fails we cannot solve in the plugin. Sometimes a test fails because the answer is slightly out of the range of the accepted values. Sometimes the Quantum Inspire backend was not responding (or unreachable).
