### ISSUE TITLE
Broaden support number of wires of hardware devices

### ISSUE THREAD

**Issue by RobertWezemanTNO** [QuTech-Delft/pennylane-quantuminspire#71]
**Is your feature request related to a problem? Please describe.**

Currently, an error is being thrown when the number of wires does not match exactly the number of qubits in case of real hardware. 

```python
import pennylane as qml
dev = qml.device('quantuminspire.qi', wires=4, backend='Starmon-5')
```

The error is raised by the if condition in `_check_backend`

```python
if backend_type["is_hardware_backend"] and number_of_wires != backend_type["number_of_qubits"]:
    raise DeviceError(
        f"Invalid number of wires: {number_of_wires}. " f'Should be exactly {backend_type["number_of_qubits"]}'
    )
```
This is not ideal, as circuits that are defined with fewer number of wires than number of qubits should be possible. In one of our applications, the number of wires is determined by input data size. 

**Describe the solution you'd like**
See this draft pull request https://github.com/QuTech-Delft/pennylane-quantuminspire/pull/70

**Acceptance criteria**
Please specify the acceptance criteria in as much detail as possible,
for example:

With the new version the following code should run with `n_features < 5`. 

```python
from tno.quantum.ml.classifiers.vc import VariationalClassifier
from tno.quantum.ml.datasets import get_wine_dataset

X_training, y_training, X_validation, y_validation = get_wine_dataset(
    n_features=4, n_classes=3, random_seed=0
)
vc = VariationalClassifier(
    backend={
        "name": "quantuminspire.qi",
        "options": {"backend": "Starmon-5", "project": "my project"},
    },
)
vc = vc.fit(X_training, y_training)
predictions_validation = vc.predict(X_validation)
```

Note: requires installing `tno.quantum.ml.classifiers.vc` and `tno.quantum.ml.datasets` (which can be done with pip).

**Additional context**

**Comment by QFer** [comment]
Solved in https://github.com/QuTech-Delft/pennylane-quantuminspire/pull/74
